Request to add object detection node and data extraction nodes
Samsung/SamsungAutomationStudio pull request #59
Opened 2022-10-02 00:26 UTC by Orchemi

### Korean

안녕하세요. Samsung SW Academy For Youth 7th의 SASM 오픈소스 프로젝트 팀 '5생활관'입니다.

Samsung Automation Studio for Mashup(이하 SASM)에 기존 motion-pose와 함께 **object detection** 요소를 추가하여 사용자가 위치한 장소에 따라 motion pose가 의도하는 플로우를 달리 할 수 있는 다형성을 확보하였습니다. 동시에 motion pose과 object의 상호작용을 분석하여 log를 남기고 이를 시각화하는 **dashboard chart**를 제작하였습니다.

또한 이 플로우에서 API를 활용해 이후 동작을 연계하는 과정에서 활용되는 **데이터 추출(data extraction) 노드**까지 제작하였습니다. 

<br>

저희가 개발한 노드들에 대한 설명을 간략하게 요약하겠습니다.

|이름|내용|
|---|---|
|`object detection`|80여 개의 사물 인식/판단 및 로그 기록|
|`object person determine`|인식된 사람과 상호작용하고 있는 사물이 무엇인지 판단|
|`log`|사물 및 사람 인식에 대한 로그 기록을 정해진 형식의 파일로 저장|
|`data extractor`|API 데이터의 특정 부분만을 선택 및 추출|
|`data filter`|API 데이터의 일부 요소가 특정 조건을 만족하는 경우 특정 부분을 선택 및 추출|

<br>

개발한 노드들에 대한 세부 내용은 아래의 링크를 참고해주시기 바랍니다.

- [object detection main](https://github.com/D5MI/node-red-contrib-object-detection/tree/master)
- [object detection node](https://github.com/D5MI/node-red-contrib-object-detection/tree/master/object_detection)
- [object person determine node](https://github.com/D5MI/node-red-contrib-object-detection/tree/master/object-person-determine)
- [log node](https://github.com/D5MI/node-red-contrib-object-detection/tree/master/log)
- [data extractor node](https://github.com/D5MI/node-red-contrib-data-extraction/tree/master/data-extractor)
- [data filter node](https://github.com/D5MI/node-red-contrib-data-extraction/tree/master/data-filter)

<br>

본 노드와 플로우를 제작하기까지 기획 및 개발 과정에서 여러 인사이트와 기술적으로 지원해주신 삼성전자 김선학 멘토님과 이진규 멘토님, 그리고 SSAFY 관계자분들께 깊은 감사를 드립니다.

<br>

### English

Hello. This is the SASM open source project team 'D5MI' of Samsung SW Academy For Youth 7th.

By adding the **object detection** element along with the existing motion-pose to Samsung Automation Studio for Mashup (hereafter referred to as SASM), polymorphism that allows the intended flow of motion pose to vary depending on the location of the user has been secured. At the same time, we created a **dashboard chart** that analyzes the interaction between motion pose and object, leaves a log and visualizes it.

In addition, using the API in this flow, **data extraction nodes** that is used in the process of linking subsequent actions was also created.

<br>

We will briefly summarize the descriptions of the nodes we have developed.

|name|description|
|---|---|
|`object detection`|recognition/judgment of over 80 objects and recording of logs|
|`object person determine`|determine which object is interacting with the recognized person|
|`log`|saves log records of object and person recognition in a file in a fixed format|
|`data extractor`|selects and extracts only a specific part of API data|
|`data filter`|select and extract a specific part of API data when some elements satisfy specific conditions|

<br>

For details on the developed nodes, please refer to the link below.

- [object detection main](https://github.com/D5MI/node-red-contrib-object-detection/tree/master)
- [object detection node](https://github.com/D5MI/node-red-contrib-object-detection/tree/master/object_detection)
- [object person determine node](https://github.com/D5MI/node-red-contrib-object-detection/tree/master/object-person-determine)
- [log node](https://github.com/D5MI/node-red-contrib-object-detection/tree/master/log)
- [data extractor node](https://github.com/D5MI/node-red-contrib-data-extraction/tree/master/data-extractor)
- [data filter node](https://github.com/D5MI/node-red-contrib-data-extraction/tree/master/data-filter)

<br>

We would like to express our deepest gratitude to mentors Seonhak Kim and Jinkyu Lee of Samsung Electronics, mentors of Samsung Electronics, and SSAFY officials for providing various insights and technical support during the planning and development process until the production of this node and flow.

2022-10-02 01:18 UTC, jg8008 requested changes

2022-10-02 01:18 UTC, jg8008 commented on data-extraction/data-filter/data-filter.js
> +  }
Code의 가독성 향상을 위해 Bubble Style을 Gateway Style로 전환해보는건 어떨까요?
아래 페이지를 참고 하시고 Clean Code 관점에서 고려를 해보시는 걸 추천드립니다.
https://eblo.tistory.com/7
https://dzone.com/articles/code-smells-if-statements

2022-10-02 01:39 UTC, jg8008 commented on object-detection/log/log.js
> +            let directory = `${config.logDirectory}`
date 변수가 ms.payload.Date에 할당 되는 것 이외에는 쓰이는 곳이 없는 거 같아 보이는데요,
아래와 같이 한줄 코드로 변경하면 어떨까요?
msg.payload.Date = today.toLocaleString()

2022-10-02 01:39 UTC, jg8008 commented on object-detection/object-detection-node.html
> +                        //context.strokeStyle = '#' + color
사용하지 않는 code는 주석 처리 보다는 삭제를 권장드립니다.

2022-10-02 01:39 UTC, jg8008 commented on object-detection/object-detection-node.html
> +                        context.fillStyle = '#2fff00';
"#2fff00", '24px Arial' 와 같은 하드코딩 된 형태는 대체로 지양해야 합니다.
const 변수와 같이 의미를 전달할 수 있는 변수의 이름으로 대체하여 사용하는 것은 어떨까요?
const FONT_24PX_ARIAL = '24px Arial'
...
context.font = FONT_24PX_ARIAL;

2022-10-02 01:39 UTC, jg8008 commented on object-detection/object-person-determine/object-person-determine.js
> +            let date = null;
변수 선언 및 초기화를 아래와 같이 해보면 어떨까요? clean code 관점에서 고려하시면 좋을 것 같습니다.
예) let inputList, isLog, date = null
nodjs에서는 문법이 다를 수 있습니다.

2022-10-02 01:39 UTC, jg8008 commented on object-detection/object-person-determine/object-person-determine.js
> +                else objects.push({ centerX, centerY, diameter, 'class': _class, distance: -1 });
_class 변수의 경우 한번 호출되는 거 같은데 아래와 같이 code를 변경하면 1줄이라고 code를 줄일 수 있을거 같네요.
objects.push({ centerX, centerY, diameter, 'class': object['class'], distance: -1 });

2022-10-02 01:39 UTC, jg8008 commented on object-detection/object_detection/object-detection.js
> +
코드에 Lint 또는 style을 적용 안한거 같아 보이네요. 의미 없는 공배줄은 삭제하면 code의 가독성을 높힐 수 있습니다.

2022-10-02 01:44 UTC, jg8008 reviewed
각 Module 또는 함수에 대한 Test Case 가 없는 것이 많이 아쉽습니다만 Project 기간이 짧기 때문에 어쩔 수 없었음을 이해합니다.
향후, 현업이나 다른 project을 진행할 때에는 TDD , BDD, DDD 개발 방식을 통해 개발 코드에 대한 test coverage를 높히는 것을 추천드립니다.

2022-10-02 01:44 UTC, jg8008 approved these changes

2022-10-05 06:55 UTC, SangWoo-Han97 commented on data-extraction/data-filter/data-filter.js
> +  }
피드백 주신 링크 참고해서 bubble style에서 gate style로 변경했습니다.

2022-10-05 06:55 UTC, SangWoo-Han97 commented on object-detection/log/log.js
> +            let directory = `${config.logDirectory}`
아래 21번 아래에서 
```
let fullPath = `${config.logDirectory}` + "/log-" + today.getFullYear()+'-'+(today.getMonth()+1)+'-'+today.getDate()
```
추가로 today 변수를 참조해야해서 사용했습니다!
(파일명이 log.js 에서 object-detection-log.js 로 변경되었습니다.)

2022-10-05 06:55 UTC, SangWoo-Han97 commented on object-detection/object-detection-node.html
> +                        //context.strokeStyle = '#' + color
주석처리된 코드와 console log 모두 삭제했습니다.

2022-10-05 06:55 UTC, SangWoo-Han97 commented on object-detection/object-detection-node.html
> +                        context.fillStyle = '#2fff00';
```
const FONT_24PX_ARIAL = "24px Arial";
const COLOR_LIME = "#2fff00";
const DEFAULT_LINE_WIDTH = 1;
```
의미 있는 변수로 대체하였습니다.

2022-10-05 06:56 UTC, SangWoo-Han97 commented on object-detection/object-person-determine/object-person-determine.js
> +            let date = null;
node.js 에서 테스트 해본 결과 `let inputList, isLog, date = null;` 문법이 적용되지 않아서 
`let inputList = null, isLog = null, date = null;` 와 같은 방식으로 수정했습니다.

2022-10-05 06:56 UTC, SangWoo-Han97 commented on object-detection/object-person-determine/object-person-determine.js
> +                else objects.push({ centerX, centerY, diameter, 'class': _class, distance: -1 });
피드백 주신대로 반영했습니다.

2022-10-15 03:09 UTC, jg8008 commented on data-extraction/data-filter/data-filter.js
> +  }
변경 확인했습니다. 감사합니다.

2022-10-15 03:10 UTC, jg8008 commented on object-detection/log/log.js
> +            let directory = `${config.logDirectory}`
반영 감사합니다.

2022-10-15 03:10 UTC, jg8008 commented on object-detection/object-detection-node.html
> +                        context.fillStyle = '#2fff00';
반영 확인했습니다. 감사합니다.

2022-10-15 03:10 UTC, jg8008 commented on object-detection/object-person-determine/object-person-determine.js
> +            let date = null;
반영 확인했습니다. 감사합니다.

2022-10-15 03:10 UTC, jg8008 commented on object-detection/object-person-determine/object-person-determine.js
> +                else objects.push({ centerX, centerY, diameter, 'class': _class, distance: -1 });
반영 확인했습니다. 감사합니다.

2022-10-15 03:11 UTC, jg8008 commented on object-detection/object_detection/object-detection.js
> +
반영 확인했습니다. 감사합니다.

2022-10-15 03:12 UTC, jg8008 approved these changes
피드백에 관한 반영사항 모두 확인했으며 7주간 OpenSource 프로젝트를 진행해주셔서 감사합니다. 수고하셨습니다.

2022-10-15 03:12 UTC, merged

2022-10-15 05:25 UTC, SangWoo-Han97 commented
7주동안 멘토링해주셔서 너무 감사했습니다!!